### ISSUE TITLE
AccountNames endpoint duplicate `accountNames` key

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#101]
Should the `AccountNames` endpoint return `[{address, names[]}]` rather than `accountNames:[{address, names[]}]`?

**Comment by Vektrat** [comment]
I'm not sure technically we can change this with the current schema implementation, and also, it is opinionated, but I prefer that REST APIs always return objects rather than arrays (not sure if the rest of the project is consistent with this)

**Comment by rg911** [comment]
cool. I am okay with either as long as they are consistent with others 👍
