### ISSUE TITLE
Receipts schema changed

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#102]
Noticed that all receipt schemas have been changed with extra `statement` key. Why this adding this extra key? and do we need it at all?

https://github.com/nemtech/catapult-rest/pull/93

**Comment by Vektrat** [comment]
it's in the accepted changes https://docs.google.com/document/d/1GpUR2Ct1DJ-VGVFGoVVGPoy_ndRmN2RcNJpNxZqapvo/edit?pli=1#
