### ISSUE TITLE
Node endpoint throw 5xx errors

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#106]
node/info
node/time

both throw 503 errors

**Comment by Vektrat** [comment]
closing because this was tested and it is working as expected

most likely missing `apiNode.timeout` property in rest config json file

**Comment by rg911** [comment]
Can you provide couple of lines here on how to add this missing config pls? to benefit others who may facing the same issue.

**Comment by Vektrat** [comment]
> Can you provide couple of lines here on how to add this missing config pls? to benefit others who may facing the same issue.

sure, though i just did 🤣  it's also visible in the template `rest.json`

```
  "apiNode": {
    "host": "127.0.0.1",
    "port": 7900,
    "publicKey": "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
    "timeout": 1000
  },
```
