### ISSUE TITLE
transactions pagination

### ISSUE THREAD

**Issue by roccomuso** [nemtech/catapult-rest#12]
Would be useful to have some pagination mechanism for API like `account/transfers/all` https://nemproject.github.io/#requesting-transaction-data-for-an-account

Or some `filter` param to get only transactions AFTER a certain ID. If I'm not wrong right now only the opposite is possible but quite useless

**Comment by Vektrat** [comment]
In regards to which endpoint are you talking about?

**Comment by roccomuso** [comment]
I was talking about `account/transfers/all`, I noticed that you can get txs up to a certain txid and txs are ordered DESC.

**Comment by Vektrat** [comment]
you can also change the ordering iirc
