### ISSUE TITLE
ws newBlock returns different payload from block endpoint

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#124]
Listening on newBlock channel, message payload is quite different from blockInfo returned from block endpoint.

**Comment by Vektrat** [comment]
unless it's specific format of attributes (for example, one address in `binary`, and the other in `hex`, we cannot help here - both objects come from core side, and they are probably supposed to be different anyway

let us know if this is the case, or if you are taking about different fields/schema and we will take a look

**Comment by rg911** [comment]
Might be worth comparing `/block/1` against the ws `block` message payload.

**Comment by rg911** [comment]
looks like it's the NF test is using the older version
