### ISSUE TITLE
Account State merkle features

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#127]
blocked by either catbuffer-js or core providing the full tree/trie - requiring implementation details (from core)

**Comment by Vektrat** [comment]
- https://github.com/nemtech/catapult-server/blob/master/src/catapult/ionet/PacketType.h#L99
- https://github.com/nemtech/catapult-server/blob/master/src/catapult/handlers/StatePathHandlerFactory.h#L33

**Comment by Vektrat** [comment]
@dgarcia360 a suggestion of endpoint structure for this would be helpful, you can check the different account state paths that can be requested here:
https://github.com/nemtech/catapult-server/blob/master/src/catapult/ionet/PacketType.h#L99

i'd suggest to have a "master" `/state/{type}` endpoint rather than appending `.../state` to the different resources, since there are many of them

**Comment by dgarcia360** [comment]
@Vektrat I'm not familiar with this feature yet, I'm trying to understand how it works first before adding my suggestion here.

Could you confirm to me if it works like ``merkleTrees``? Meaning you pass first to the endpoint the block height and some information about the state (probably a hash). Then, the endpoint returns the path if it's the state hash belong to the specified block. From this path and the state hash, you can build the ``stateHash`` from the block header.

Also, do you know how to get the ``AccountState`` hash for a given account?

**Comment by Vektrat** [comment]
it works exactly like merkle trees from the client perspective

i don't really know where the `AccountState` hash is provided, this is a question fore core, i'm also unsure about the order in which the hashes are listed, feel free to answer below

https://nem2.slack.com/archives/GMUA2SD7E/p1571659200006600

**Comment by dgarcia360** [comment]
Let me know what do you think about the following proposal:

**GET** ``/block/{height}/state/{state}/hash/{hash}/merkle``

Returns the merkle path if the state hash belong to the block.

**Parameters**

{state} -> Enumeration:

| Id | Type |
| --- | ----- |
|  800 + 0x43  | Account_State_Path |
|  800 + 0x48 | Hash_Lock_State_Path |
|  800 + 0x52 | Secret_Lock_State_Path |
|  800 + 0x44 | Metadata_State_Path |
|  800 + 0x4D | Mosaic_State_Path |
|  800 + 0x55 | Multisig_State_Path |
|  800 + 0x4E | Namespace_State_Path |
|  800 + 0x50 | Account_Restrictions_State_Path |
|  800 + 0x51 | Mosaic_Restrictions_State_Path |

* {hash} ->state hash (tree leaf).  The SDK must serialize + hash states to be able to use the feature. This will be possible once the catbuffer library defines [states](https://github.com/nemtech/catbuffer/tree/crackTheCode016/update/serialization-schemas).

**Responses**
* **200** - Ok. 

Example:

``{
"merklePath": [
{
"position": 1,
"hash": "C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810"
}
]
}``

* **404** - Not Found
* **409** - Invalid Argument

**Comment by Vektrat** [comment]
@dgarcia360 two matters:

- should we keep the `/merkle` at the end? or switch it with `/patricia`? since the provided structures are patricia trees, not specifically merkles
- right now core implementation only supports requesting `current` block states, hence the `/block/:height` part of the query seems a bit redundant now, should we keep it?

**Comment by dgarcia360** [comment]
> should we keep the /merkle at the end? or switch it with /patricia? since the provided structures are patricia trees, not specifically merkles

It's a merkle patricia tree, so it still is a merkle tree somehow. @Jaguar0625 do you think it is necessary to clarify the ``patricia`` part in the endpoint?

> right now core implementation only supports requesting current block states, hence the /block/:height part of the query seems a bit redundant now, should we keep it?

After talking with core devs it _might_ be possible, but not tested yet. We can start small, doing only current height, and evolve the endpoint in the future if it's needed. In short, the proposed endpoint could be modified as follows:

``GET /state/{state}/hash/{hash}/merkle``

Returns the merkle path if the state hash belongs to the current block.

**Comment by Vektrat** [comment]
this will need to be tested, documentation was lacking and i didn't have tools to serialize and hash the resources

@fboucquez @rg911 

also @dgarcia360 feel free to update docs with the latest suggestion (i didn't put `/block/X` in it yet because it makes no sense)
