### ISSUE TITLE
/Mosaic getMosaics (POST) endpoint server error

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#132]
Endpoint: `http://localhost:3000/mosaic`
Body payload: 
```
{
	"mosaicIds": ["3152746411B1D67B"]
}
```
Internal error:

```
{
    "code": "Internal",
    "message": "Topology was destroyed"
}
```

**Comment by martinayora** [comment]
Can you check that this mosaic is in the database? I get this same error when databased is cleared with no notice. It has to do more with the conection to the database (and maybe mongo caches) than the rest server itself.

https://stackoverflow.com/questions/30909492/mongoerror-topology-was-destroyed

When it happens to me, I shut down the ssh tunnel, wait for some minutes and I try again.

**Comment by rg911** [comment]
Pretty sure it worked before. I will try the ssh reset 👍

**Comment by rg911** [comment]
seems to be my own ssh issue
