### ISSUE TITLE
new metadata endpoint internal error when using address

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#137]
```
{
    "code": "Internal",
    "message": "db.addressToPublicKey is not a function"
}
```

**Comment by Vektrat** [comment]
oh f*ck

**Comment by Vektrat** [comment]
did you build the sdk?

**Comment by rg911** [comment]
Yeah, SDK calls failed as well. 

`http://localhost:3000/account/9F784BF20318AE3CA6246C0EC2207FE095FFF7A84B6787E7E3C2CE4C3B92A2EA/metadata`

**Comment by martinayora** [comment]
We mean the catapult-sdk inside catapult-rest project.  _yarn run build_ ?

**Comment by martinayora** [comment]
Can you paste the call you are executing?

**Comment by rg911** [comment]
/account/SD36VT5ZMDIGWDKIEIISOJSCQ5EYP4KGNZBDQZFM/metadata
