### ISSUE TITLE
Include the address in the WebSocket Message/Payload

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#141]
Hi team, would it be possible to add the plain address of the account that fire the web socket events that are related to an account?

For example in the status message:

{"hash":"...","status":"...","deadline":"...", **"address":"SDTP652VVAFWVKJVUXBRW3J5BT5PQLQGX4VZZSPA"**}

It will simplify the listener implementation in the SDK. Especially when one SDK listener is handling events from multiple accounts.

**Comment by Vektrat** [comment]
i'm sorry but it is not up to the REST server to decide which fields are included in the web socket data, the REST server forwards whatever comes from core side, so this should be escalated to Greg/Victor or alike, and this data should be provided by the core

**Comment by fboucquez** [comment]
Is rest implementing WebSockets? When sending a payload to that channel you know the address right?

**Comment by Vektrat** [comment]
serialized and signed payload is pushed to the network via the announce endpoint, afterwards, if the transaction is received by the node and is valid, asynchronous feedback is reported via the ws listener, which is a different channel, i'm unsure if i'm fully understanding what you'd like to have here but i believe you want to make a "connection" between the sent payload, and the asynchronous listener feedback afterwards

**Comment by fboucquez** [comment]
Hi @Vektrat ,

https://github.com/nemtech/catapult-rest/blob/master/rest/src/connection/MessageChannelBuilder.js#L98

I can see catapult rest is creating the payload. Is it possible to add the address there?

**Comment by Vektrat** [comment]
> Hi @Vektrat ,
> 
> https://github.com/nemtech/catapult-rest/blob/master/rest/src/connection/MessageChannelBuilder.js#L98
> 
> I can see catapult rest is creating the payload. Is it possible to add the address there?

why do you ask me if you don't trust my answers and go look for yourself? :)

as i already said before, what the rest is forwarding is data received from the core, REST is just fetching it and making a cute answer out of serialized data so that it can be read, as you can see at core side, we are not getting the address, so this needs to be escalated

https://github.com/nemtech/catapult-server/blob/master/src/catapult/model/TransactionStatus.h

**Comment by fboucquez** [comment]
What about the topic param? That's the address right?

https://github.com/nemtech/catapult-rest/blob/2de71cacfbf31f7408d9d52fb796197bd4ce78dc/rest/src/connection/MessageChannelBuilder.js#L46

I think this improvement is valid. if it cannot be implemented now due to
time/priority/dependencies it doesn't mean it has to be closed permanently.

**Comment by Vektrat** [comment]
it's not a time issue it's that we are not deciding what data we receive, but i will dedicate some time to this, already asked the core devs for input and i'll check the topic reference

**Comment by fboucquez** [comment]
Thanks Roger.

Maybe just adding the topic and the topic param (if any, most likely the
address) to the payload will help the SDK and the clients to do a better
event dispatching in this side of the fence. It will help scaling the
listeners.

**Comment by Vektrat** [comment]
sorry had issues with the environment, i've been working on this for a while (it's an easy change, but testing it is a bit annoying)

**Comment by fboucquez** [comment]
Hi team, I've found an issue. The topic includes the marker chart. It's not an encoded address. The SDK could take out the marker but it would be wrong. It's an internal mark.

https://github.com/nemtech/catapult-rest/blob/master/rest/src/connection/MessageChannelBuilder.js#L90

The first byte needs to be removed from the topic. 

I'm going to push a PR once I have permission to push in NEMStudios
