### ISSUE TITLE
redundant key in mosaic restriction payload

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#146]
`mosaicRestrictionEntry` looks redundant in mosaic restriction payloads

**Comment by Vektrat** [comment]
there was a great discussion around this , we remade this a few times always finding problems trying new implementations, in the end we decided to go with this approach, which is what mongoDb is feeding us

**Comment by Vektrat** [comment]
apparently openapi needs updating, but this is fine afaik
