### ISSUE TITLE
Mosaic Info endpoint still has properties nested object

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#156]
Hi team, 

Rest is returning the following JSON when asking for the mosaic info:

![image](https://user-images.githubusercontent.com/5390558/66166302-3cd9b080-e637-11e9-8c5b-a3a38b924c85.png)

The open API defines MosaicDto like this:

![image](https://user-images.githubusercontent.com/5390558/66166311-419e6480-e637-11e9-95a2-41b4cf74efe6.png)

As far I remember, properties were merged to the top-level Mosaic object. @dgarcia360 ?

**Comment by Vektrat** [comment]
not a REST issue, the core you are using is not updated to the latest version

**Comment by dgarcia360** [comment]
@Vektrat just to make sure, do we have to change something in the latest swagger spec?

**Comment by Vektrat** [comment]
hm probably, core changed mosaicDTO sothat it does not have a `properties` object anymore, instead, this object was removed and the 3 properties inside (duration, flags, divisibility?) it were put at the outer level
