### ISSUE TITLE
MosaicSupplyChangeTransaction uses direction field when it should be action

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#157]
The current master uses "direction" field when serializing MosaicSupplyChangeTransaction to JSON. Current open API spec defines the "action" field

The json payload
![image](https://user-images.githubusercontent.com/5390558/66312195-7bf65300-e910-11e9-88aa-4aa513608672.png)

The open api spec
![image](https://user-images.githubusercontent.com/5390558/66312213-83b5f780-e910-11e9-8304-719192c49ec1.png)

**Comment by Vektrat** [comment]
REST does not decide what fields are shown or what name those fields have, this is a question for core

but anyway, I just checked and currently, `action` is being used both at core (mongodb) and at REST side, i'm not sure what version of core you are using but this is definitely not a REST issue, unless core admits this has changed very recently in some version that we still cannot see at rest side
