### ISSUE TITLE
Change mosaic restriction restrictionKey field to hex instead of numeric string

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#160]
Addresses https://github.com/nemtech/nem2-openapi/pull/35

**Comment by fboucquez** [comment]
Open api also specify that the key in the endpoints is a hex

![image](https://user-images.githubusercontent.com/5390558/66385829-6e4cd600-e9c1-11e9-9764-9f9f9c2eabf2.png)

![image](https://user-images.githubusercontent.com/5390558/66385848-76a51100-e9c1-11e9-940a-174fb97c33f3.png)

Is this going to be converted to hex too? For consistency, restriction key should have the same format in the transactions and in the endpoints data

**Comment by Vektrat** [comment]
@dgarcia360

**Comment by dgarcia360** [comment]
@fboucquez ``MosaicGlobalRestrictionEntry`` and ``MosaicAddressRestrictionEnty`` id properties were already tagged with ``format:hex``, they will remain the same (hex).

**Comment by Vektrat** [comment]
are you guys talking about the same?

in REST `mosaicId` and `referenceMosaicId` are HEX, but everything else (`key`, `value`, `restrictionKey`, `restrictionValue`) is formatted as numeric string

**Comment by Vektrat** [comment]
@dgarcia360 we will have HEX jut in `mosaicId`, `referenceMosaicId`, and `restrictionKey`, is that correct?

**Comment by rg911** [comment]
@Vektrat I believe that's the plan. @dgarcia360

**Comment by dgarcia360** [comment]
Looks correct for MosaicGlobalRestrictionTransaction. For MosaicAddressRestrictionTransaction only ``mosaicId`` and ``restrictionKey`` as there is no ``referenceMosaicId``.

**Comment by fboucquez** [comment]
Hi @Vektrat, sorry for the later response. I had this plugin issue on my catapult-rest

Is it possible that the MosaicAddressRestrictionEntryDTO and MosaicGlobalRestrictionEntryDTO restriction keys are still in a numeric string, not hex?

**Comment by Vektrat** [comment]
> MosaicAddressRestrictionEntryDTO

yes they are not hex, because i asked twice here and i got confirmation that `key` should not be hex - only `mosaicId`, `restrictionKey`, and `referenceMosaicId` were supposed to be hex
