### ISSUE TITLE
Transaction endpoint returns empty array for accounts of which the public key is unknown by the network

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-rest#164]
Now we can query the transactions with an address instead of a public key, however, if one account has received coins, but has not sent transactions, account/address returns accountInfo with up-to-date account balance, but transactions/endpoint returns an empty array, which seems a bit odd

**Comment by Vektrat** [comment]
we are investigating this, but it may be a bit tricky to solve (we saw on slack, thanks for opening an issue)
