### ISSUE TITLE
Allow to filter transactions by type

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#166]
https://nem2.slack.com/archives/CEZKUE4KB/p1571386513062000

**Comment by Vektrat** [comment]
@dgarcia360 what do you think about this?

**Comment by dgarcia360** [comment]
It looks valid to me as well, although I'd pass the [transaction type (id)](https://nemtech.github.io/concepts/transaction.html#transaction-types) instead of a string like "transfer".

**Comment by Vektrat** [comment]
yep, i prefer this as well, clients can mask this in an enum

**Comment by Vektrat** [comment]
David's suggestion accepted then, should be applied to this set of endpoints:
```
routeUtils.addGetPostDocumentRoutes(
			server,
			sender,
			{ base: '/transaction', singular: 'transactionId', plural: 'transactionIds' },
```

**Comment by Vektrat** [comment]
David's suggestion accepted then, should be applied to this set of endpoints:
```
server.get(`/account/:accountId/transactions${state.routePostfix}`, (req, res, next) => {
server.get('/account/:accountId/transactions/incoming', (req, res, next) => {
```

**Comment by Vektrat** [comment]
@44uk

**Comment by 44uk** [comment]
Thanks! I think this is reasonable way.

**Comment by Vektrat** [comment]
kind of blocked by #214

**Comment by Vektrat** [comment]
@dgarcia360 this will be worked on imminently

**Comment by 44uk** [comment]
It's great!
