### ISSUE TITLE
Refactor pagination (includes transaction endpoints review)

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#172]
Currently it is heavily bound to the paginated resources (relying on them having `meta`, `_id`, etc)

The proposed approach will result in the following:

config:
```
defaultPageSize (?)
minPageSize
maxPageSize
```

requests will accept the following query params:
```
page
pageSize
```

results will be of the following shape:
```
{
    data: [],
    paging: {
        page: X,
        pageSize: X,
        dataCount: X
}
```

_naming not necessarily definitive (eg. instead of data, it could be: results, records, entities, values, etc)_ 

if in the future we see that results shifting due to data being updated in the middle of paging is an issue, we can add the option to lock the results with a specific param (`from`)

**Comment by Vektrat** [comment]
the `step` parameter is an annoyance that binds clients to specific pagination rules, this was initially set so that block requests would benefit from caching full pages, but currently no caching system has been deployed or tested - removing this would improve client freedom on other requests

**Comment by evias** [comment]
@Alexhuszagh can you please have a look here and coordinate with us on what you did with pagination in that regards? (the "steps" problematic)

**Comment by Alexhuszagh** [comment]
@evias @Vektrat I actually just removed the step parameter entirely (and the idea of concrete pages, rather, I'm working with timelines), and therefore allowed a request to specify a range of values they would want (currently set to anything from 1-100, but could be set to any arbitrary value). This avoids binding clients to specific pagination rules, and the actual logic is here:

```
	/**
	 * Parses a value with valid, acceptable range values.
	 * @param {any} str Value to parse.
	 * @param {object} range Range of valid values.
	 * @param {Function|string} parser Parser to use or the name of a named parser.
	 * @returns {object} Parsed value or undefined.
	 */
	parseRangeValue(str, range, parser) {
		const value = this.parseValue(str, parser);
		if (value < range.min)
			return undefined;
		if (value > range.max)
			return undefined;
		return value;
	},
```

Simply, it works as before, except it accepts a range of values, IE, anything within a min or max, optionally provided (with a default value), to sidestep the `step` parameter.

**Comment by Vektrat** [comment]
why isn't removing the step enough?

**Comment by Alexhuszagh** [comment]
@Vektrat You likely could, to my knowledge, you only have pagination for your methods with blocks, so it would be trivial to remove that entirely. Just then accept a valid range, and create the actual block heights from there.

**Comment by Vektrat** [comment]
this was not done becuase we were pending on the refactor of how we deal with query params in general, since this is a subset of those #39 

since we don't know when that task will be finished, we will post a quick patch to address the pagination restriction on %25 #233

**Comment by Vektrat** [comment]
params refactor proved to be more troublesome than expected (too many major changes), and it was just an internal improvement, so we have decided to move forward with this issue

**Comment by fboucquez** [comment]
What's the status of this issue? We would like to start to dong the SDK pagination features too

**Comment by Vektrat** [comment]
we are still discussing, SDK pagination should not begin until it's ready at REST side

**Comment by fboucquez** [comment]
The Open API spec proposal is being discussed here

https://github.com/nemtech/symbol-openapi/pull/92

**Comment by Vektrat** [comment]
Merged https://github.com/nemtech/catapult-rest/pull/300
