### ISSUE TITLE
partialAdded ws and transactions/partial not returning expexted transaction

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-rest#173]
Scenario:
The account `C` has 2 cosigners: `A` and `B`, and a `minApproval` of 2
`A` announces a `TransferTransaction` from `C` to any address

Expected:
Using `B`'s address as a parameter passed to `partialAdded` ws, or to `transactions/partial` should return the transaction to be cosigned

Actual:
The transaction to be cosigned is only returned using `A` and `C` address

**Comment by Vektrat** [comment]
i believe this is a duplicate issue of https://github.com/nemtech/catapult-rest/issues/10

i started taking a look at this the last week, and will probably get fixed by the next one (no promises ^^)

**Comment by decentraliser** [comment]
I'm not sure it is, #10 is about multisig modification

**Comment by Vektrat** [comment]
yeah this is why i'm not closing this yet, will take both into consideration when attempting to fix the other one

**Comment by decentraliser** [comment]
The thing is that #110 was a problem way before the one I describe. IIRC in Cow and Dragon, listening to partial transactions was OK

**Comment by Vektrat** [comment]
closing, confirmed it works https://github.com/nemtech/catapult-rest/issues/10#issuecomment-566922069
