### ISSUE TITLE
MosaicSupplyChange rename direction for action 

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#175]
According to the open api spec, MosaicSupplyChange Transactions should have an "action" field, not a "direction" field.

https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2496

It seems like the catapult-sdk is still using the direction field.

https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/plugins/mosaic.js#L81

The field should be renamed to action.

![image](https://user-images.githubusercontent.com/5390558/67684338-45ea4300-f993-11e9-8c34-0121c220d432.png)

**Comment by Vektrat** [comment]
this field is irrelevant to this issue, it's just internal naming, the problem you are having is because the mongodb database you are using is outdated - please check and reopen if i'm wrong

**Comment by fboucquez** [comment]
I've cleared up my catapult-service-bootstrap, running the latest images and the latest catapult-rest from master. In the code, there are references to "direction". 

Martin is working on this related PR. 
https://github.com/nemtech/catapult-rest/pull/176

Is this issue an env problem?

**Comment by Vektrat** [comment]
as i said, PR won't fix this, and it is not an env problem, it is a problem with the current mongodb version - the references to direction have nothing to do with the issue here
