### ISSUE TITLE
Importance score reflection delay

### ISSUE THREAD

**Issue by evias** [nemtech/catapult-rest#194]
**Expected behavior**

The /account/{accountId} endpoint should return the `importances` entry that is nearest to the current block height.

**Actual behavior**

The /account/{accountId} endpoint return delayed information as explained in following: 

- At chain height `188614` the rest query shows an importance height of `188526`, which is wrong. **It should show the importance height of `188604`.**

- The database has as importances entries:

```
"importances" : [
  {
    "value" : NumberLong("2690476621060"),
    "height" : NumberLong(188604)
  },
  {
    "value" : NumberLong("2690476621060"),
    "height" : NumberLong(188565)
  },
  {
    "value" : NumberLong("2690476621060"),
    "height" : NumberLong(188526)
  }
]
```

- So the problem is that rest is returning the wrong entry from the importance array

**Environment**

REST v0.7.20

**Comment by Vektrat** [comment]
waiting for feedback/confirmation

https://nem2.slack.com/archives/CEZKUE4KB/p1573580743172100?thread_ts=1573219919.124600&cid=CEZKUE4KB

**Comment by Vektrat** [comment]
confirmed changed on elephant

**Comment by evias** [comment]
Re-opening due to invalid importance score displayed in account info:

I still don’t seem to see the correct importance with latest REST master, following is the accountInfo : 

```
{
  "account": {
    "address": "98DAD0DFE1E7049C9606A7EE037B528493075B1C7F540161E3",
    "addressHeight": "71",
    "publicKey": "6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C",
    "publicKeyHeight": "74",
    "accountType": 1,
    "linkedAccountKey": "1532C13BE2C5B11F2E6979CDD0AC7C463CE477BF041CDFEC32A23E2885D92BCA",
    "activityBuckets": [
      {"startHeight": "1433", "totalFeesPaid": "999936", "beneficiaryCount": 0, "rawScore": "2849334668440"},
      {"startHeight": "1", "totalFeesPaid": "13997711",  "beneficiaryCount": 0, "rawScore": "0"}
    ],
    "mosaics": [...],
    "importance": "0",
    "importanceHeight": "1433"
  }
}
```

You can see that it seems to use the correct *bucket* (“startHeight: 1433”) but doesnt seem to use correct importance (0 instead of 2849334668440)

**Comment by Vektrat** [comment]
i'm not sure where the data you are posting here is from...

i've just tested this endpoint with some data and it seems to be working just fine, is the importance of the database you are requesting against different from 0?

**Comment by evias** [comment]
Ok i understand ; I wrongly assumed that the `rawScore` of the activity bucket was to be used in the `importance` but that is wrong because the importance score is only going to be updated with next activity bucket :+1:
