### ISSUE TITLE
Incorrect transaction status codes

### ISSUE THREAD

**Issue by ravitej-aluru** [nemtech/catapult-rest#202]
Description:
Incorrect status codes end up on the client, while the server logs show correct status code.

Steps:

1. Run the following scenario  
Scenario: 1. An account blocks receiving transactions containing a specific asset
    Given Bobby blocks receiving transactions containing the following assets:
      | ticket  |
      | voucher |
    When Alex tries to send 1 asset "ticket" to Bobby
    Then Bobby should receive a confirmation message
    And Alex should receive the error "Failure_RestrictionAccount_Mosaic_Transfer_Prohibited"
2. Observe the server logs. You'll notice Failure_RestrictionAccount_Mosaic_Transfer_Prohibited in the logs. This means that the server returns the correct error code.
3. However, upon letting the error propagate to the client, you'll see Failure_RestrictionAccount_Operation_Type_Prohibited

Comparing https://github.com/nemtech/catapult-server/blob/v0.9.0.1/plugins/txes/restriction_account/src/validators/Results.h to catapult-sdk/src/model/status.js it looks like the codes are off by 1. For example, 
/// Validation failed because the mosaic transfer is prohibited by the recipient.
DEFINE_RESTRICTION_ACCOUNT_RESULT(Mosaic_Transfer_Prohibited, 12);

**_should translate to_** 
case 0x8050000**C**: return 'Failure_RestrictionAccount_Mosaic_Transfer_Prohibited';

**_but is_** 
case 0x8050000**B**: return 'Failure_RestrictionAccount_Mosaic_Transfer_Prohibited';

**Comment by Vektrat** [comment]
thanks for the detailed report

**Comment by Vektrat** [comment]
https://nemstudios.slack.com/archives/DK0FX8U72/p1574328643000700
