### ISSUE TITLE
F2 - WS failed to send confirmation message on Metadata transactions

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#203]
Announcing metadataTx never get confirmed

**Comment by fboucquez** [comment]
I'm reviewing the latest aggreagate.js. Is it possible that the padding after each inner transaction is not there yet?

**Comment by Vektrat** [comment]
probably fixed with the aggregate padding commits

**Comment by Vektrat** [comment]
closing because this is most likely fixed by the mentioned commits (`aggregate` related)
