### ISSUE TITLE
Invalid error message when metadata not found.

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#206]
The problematic endpoint is /metadata/account/{accountId}/key/{key}/sender/{publicKey} but it could be more...

![image](https://user-images.githubusercontent.com/5390558/69321769-f7ebf680-0c43-11ea-98fe-1bba1d1ffed9.png)

The account id doesn't exist, the provided value was SDTP652VVAFWVKJVUXBRW3J5BT5PQLQGX4VZZSPA

**Comment by martinayora** [comment]
The error message is correct but maybe is not very user friendly. We can treat that as a future improvement.

**Comment by fboucquez** [comment]
Yes, future improvement. If rest can be more specific, Example: Key x not found, Account y not found Signer Z not found. Etc.

**Comment by Vektrat** [comment]
we need to refactor how exceptions are handled in general, i'm not a fan of the current messages anyway, they are human readable but not very helpful technically

**Comment by fboucquez** [comment]
The improvement I see is to tell the user which parameter is the one failing or not found. In this case could be the account, the key or the signer.

An account with id xxx doesn't exist
Metadata with key ''yy' doesn't exist
Sender with public key 'zzz' doesn't exist.

**Comment by Vektrat** [comment]
closing because this forms part of a bigger task that was already due, this subtask will be pending on the referenced issue
