### ISSUE TITLE
Get transactions by address

### ISSUE THREAD

**Issue by martinayora** [nemtech/catapult-rest#214]
Review which transactions can be retrieved by address in addition to public key.

https://github.com/nemtech/catapult-rest/blob/bd4f912fbf98cbfb85ae66e4d0f21ecb993060bd/rest/src/routes/accountRoutes.js#L70-L93

**Comment by Vektrat** [comment]
we've finally come up with a way to get by this along @dgarcia360 , the implementation requires custom actions for each group of transactions and we expect this to take about 2-3 days to complete
