### ISSUE TITLE
error on unconfirmedAdded channel with aggregate transactions

### ISSUE THREAD

**Issue by evias** [nemtech/catapult-rest#221]
Using latest REST build I am getting the following error:

`aggregate cannot have partial cosignatures`

```
error: zmq unconfirmedAdded/TDNNBX7B44CJZFQGU7XAG62SQSJQOWY4P5KACYPD: error from zsocketaggregate cannot have partial cosignatures {"stack":"Error: aggregate cannot have partial cosignatures\n    at Object.deserialize (/app/catapult-sdk/_build/plugins/aggregate.js:157:12)\n    at codecs.forEach.codec (/app/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:121:34)\n    at Array.forEach (<anonymous>)\n    at Object.deserialize (/app/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:120:12)\n    at exports.Socket.<anonymous> (/app/rest/_build/connection/MessageChannelBuilder.js:55:29)\n    at exports.Socket.emit (events.js:198:13)\n    at exports.Socket.EventEmitter.emit (domain.js:448:20)\n    at exports.Socket.Socket._emitMessage (/app/rest/node_modules/zeromq/lib/index.js:649:15)\n    at exports.Socket.Socket._flushRead (/app/rest/node_modules/zeromq/lib/index.js:660:10)\n    at exports.Socket.Socket._flushReads (/app/rest/node_modules/zeromq/lib/index.js:696:15)","timestamp":"2019-12-03T05:16:17.368Z"}
```
<img src="https://user-images.githubusercontent.com/141805/70022743-81c98700-1595-11ea-9a4f-ba66fadbe4f8.png" />

Telling me it is not OK for an aggregate to have partial cosignatures. I don't really understand this error, can you shed some light, @martinayora @Vektrat ?

This happens when I announce an aggregate complete transaction and am listening to the /unconfirmedAdded/{accountId} channel (where accountId is an address).

The transaction went through correctly and got confirmed too, I also did **not** receive a notification on the /confirmed channel.

--

This is the transaction as listed on REST: http://api-01.eu-central-1.nemtech.network:3000/transaction/F9BCFC4FA2EC5F85AD44C637D5DC8303974F8A0244003303F97A9BDFEE440B33

And this is the REST error line: https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/plugins/aggregate.js#L154

**Comment by Vektrat** [comment]
are you sure it is the _latest_ REST? please provide `/diagnostic/server` info

**Comment by Vektrat** [comment]
nm, fetched from your host link, it's not the latest REST, this was fixed in the last commit

**Comment by evias** [comment]
No this also happens with a server that uses 

```{"serverInfo":{"restVersion":"1.0.20.1","sdkVersion":"0.7.20.1"}}````

**Comment by evias** [comment]
This **issue is still active with latest master** ...

**Comment by Vektrat** [comment]
example transaction failing given to me:

```5802000000000000195DAC38FF987F6A21C74683A88B0F16C330F0DD556FCF29D9F7097FF50DB570885266DF95B87D5597D9ED5A5BB5F56FA84673F4E7E762A07E82F5F69CE1B1086BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C000000000198414140420F000000000025A308FF1A000000B1FFA3550C33DB4E6386DE29075C64B3DC98031B423AFC6A8C077B75601A14B5B00100000000000045000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984E41400D0300000000007A03660A24D505B20003736C7400000046000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984E417A03660A24D505B2629035D4EB0FFE92010463616C6C000048000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984E41629035D4EB0FFE92F54025D4A45C18830106746F6B656E7346000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984D41DCAE95DABEA8F60120A1070000000000246FB4290200000041000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984D42DCAE95DABEA8F6014870040000000000010000000000000041000000000000006BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C0000000001984E43F54025D4A45C1883DCAE95DABEA8F6010100000000000000```

```{"meta":{"height":"33908","hash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","merkleComponentHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","index":0,"id":"5DE6D76C9FF86B350354A8A0"},"transaction":{"signature":"195DAC38FF987F6A21C74683A88B0F16C330F0DD556FCF29D9F7097FF50DB570885266DF95B87D5597D9ED5A5BB5F56FA84673F4E7E762A07E82F5F69CE1B108","signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16705,"maxFee":"1000000","deadline":"115947905829","cosignatures":[],"transactions":[{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":0,"id":"5DE6D76C9FF86B350354A8A1"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16718,"registrationType":0,"duration":"200000","id":"B205D5240A66037A","name":"slt"}},{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":1,"id":"5DE6D76C9FF86B350354A8A2"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16718,"registrationType":1,"parentId":"B205D5240A66037A","id":"92FE0FEBD4359062","name":"call"}},{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":2,"id":"5DE6D76C9FF86B350354A8A3"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16718,"registrationType":1,"parentId":"92FE0FEBD4359062","id":"83185CA4D42540F5","name":"tokens"}},{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":3,"id":"5DE6D76C9FF86B350354A8A4"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16717,"nonce":699690788,"id":"01F6A8BEDA95AEDC","flags":2,"divisibility":0,"duration":"500000"}},{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":4,"id":"5DE6D76C9FF86B350354A8A5"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":16973,"mosaicId":"01F6A8BEDA95AEDC","action":1,"delta":"290888"}},{"meta":{"height":"33908","aggregateHash":"2E09504B17296774D6F345F7DC7E83A8758FE8B70A2329BD2660AF9E925D4170","aggregateId":"5DE6D76C9FF86B350354A8A0","index":5,"id":"5DE6D76C9FF86B350354A8A6"},"transaction":{"signerPublicKey":"6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C","version":1,"network":152,"type":17230,"namespaceId":"83185CA4D42540F5","aliasAction":1,"mosaicId":"01F6A8BEDA95AEDC"}}]}}```

breakdown:
```58020000

00000000
195DAC38FF987F6A21C74683A88B0F16C330F0DD556FCF29D9F7097FF50DB570885266DF95B87D5597D9ED5A5BB5F56FA84673F4E7E762A07E82F5F69CE1B108

6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C

00000000

01

98

4141

40420F0000000000

25A308FF1A000000

B1FFA3550C33DB4E6386DE29075C64B3DC98031B423AFC6A8C077B75601A14B5

B0010000

00000000


/* INNER TXES START */

/* SUBTX 1 register namespace */
45000000 // 69
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4E41
400D030000000000
7A03660A24D505B2
00
03
736C74
000000

/* SUBTX 2 register namespace */
46000000 // 70
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4E41
7A03660A24D505B2
629035D4EB0FFE92
01
04
63616C6C
0000

/* SUBTX 3 register namespace */
48000000 // 72
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4E41
629035D4EB0FFE92
F54025D4A45C1883
01
06
746F6B656E73

/* SUBTX 4 mosaic definition */
46000000 // 70
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4D41
DCAE95DABEA8F601
20A1070000000000
246FB429
02
00
0000

/* SUBTX 5 mosaic supply change */
41000000 // 65
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4D42
DCAE95DABEA8F601
4870040000000000
01
00000000000000

/* SUBTX 6 alias mosaic */
41000000 // 70
00000000
6BE37B726EEE24C4B0E3C943E09A44691553759A89E92C4A84BBC4AD9AF5D49C
00000000
01
98
4E43
F54025D4A45C1883
DCAE95DABEA8F601
01
0000000000
0000```

trying to understand the last transaction's size and its last zeros

**Comment by Vektrat** [comment]
closed, it's working fine
