### ISSUE TITLE
Allow to filter transactions  using multiple types

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#240]
Now that we can filter transactions by type #166, we can iterate over the solution and add the possibility to pass multiple transaction types (enums), separated by commas.

**Example:**

> http://localhost:3000/account/{accountId}/transactions/incoming?type={type1},{type2},...,{typeN}

I found this requirement when requesting for transfer transactions inside and outside aggregate transactions.

**Comment by Vektrat** [comment]
sounds good, will see if this waits until param refactor, thinking of doing it the next
