### ISSUE TITLE
Retrieve transaction status raising an error

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#245]
**1. Expected behavior and actual behavior.**

REST is raising the error ``{"code":"Internal","message":"Cannot convert undefined or null to object"}`` when trying to get the reason why a NamespaceRegistrationTransaction was not confirmed.

**URL raising the error:** http://api-20.us-west-1.nemtech.network:3000/transaction/44365B8E4A58744877D78AB73A24330FC6317EE7F5FC0F32B13AA948D0796F4B/status

**Account submitting the transaction**: ``TBSZ63-4WDOAV-UMOMUO-ATR2VE-7U5MRD-FBL5PS-RC3K``

**Tx payload:** `97000000000000004CDC7FAE5CC3F38600F3D5B52032C7295E90B2FC6742A3F7E67FAACC0D296D6D8C01CF839472676850F8A4A72899DC4BB4EC0D1FE602E423FEB0189192EAF505CC499067D981CB2EA28D43537D8B3D91E1E0A1F7DA12DB135C1B9867DB80553B0000000001984E4140420F0000000000A3D0968101000000E80300000000000039B06A2287E046CB00056F74657374`

**2. Steps to reproduce the problem.**

1. Announce a NamespaceRegistrationTransaction with NEM2-SDK or NEM2-CLI.
2. Fetch the tx status.

**3. Specifications like the version of the project, operating system, or hardware.**

* NEM2-SDK 0.16.3
* NEM2-CLI 0.16.2

**Comment by Vektrat** [comment]
so far we confirmed transfer transactions are working, we will try with namespace next

```
{
  "hash": "3CAACD93E283AF8E8F1B7D748571A7EFF01620A018B3A4C1EC1B30199BE535B9",
  "code": "Failure_Core_Invalid_Address",
  "deadline": "6782112691",
  "group": "failed"
}```

**Comment by Vektrat** [comment]
we just tried an unconfirmed namespace registration transaction and it is also working

```{
  "hash": "F677FAA1B194D344DC56B5582A1745EB42740BD1BF61C889AA7A2BAE4CE08EF8",
  "code": "Failure_Namespace_Owner_Conflict",
  "deadline": "6782886913",
  "group": "failed"
}```

**Comment by dgarcia360** [comment]
Ok, closing the issue. The problem should be then in the custom version that the test network is using @evias
