### ISSUE TITLE
Cross-Origin Request Blocked for mosaic/names route

### ISSUE THREAD

**Issue by QuantumMechanics** [nemtech/catapult-rest#25]
Hi,

I get CORS issue when trying to fetch mosaics names

_"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://xxx.xxx.xx.xx:3000/mosaic/names. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."_

All other requests work fine so I guess it is a server-side problem.

I am using the latest Catapult docker from https://github.com/tech-bureau/catapult-service-bootstrap

Screenshots:

![c_cors_1](https://user-images.githubusercontent.com/8740532/56984139-a3890880-6b85-11e9-9394-b890f17b296f.png)
![c_cors_2](https://user-images.githubusercontent.com/8740532/56984140-a3890880-6b85-11e9-9f7c-988f524a0365.png)
![c_cors_3](https://user-images.githubusercontent.com/8740532/56984141-a3890880-6b85-11e9-8111-73ee813f8951.png)

Thanks

**Comment by Vektrat** [comment]
I'm not sure the CORS is at fault here, it may be misleading, are you sure you have the latest version of the REST server, and that the mosaics plugin is enabled within the `rest.json` config file?

**Comment by QuantumMechanics** [comment]
> are you sure you have the latest version of the REST server

It is 1.0.14

>  it is likely that this endpoint is not yet available in your catapult-service-bootstrap release

Ha yes, looking at the commits it has been added to rest after 1.0.14 release

I hope to see this added in the catapult-service-bootstrap soon. Thanks
