### ISSUE TITLE
Add endpoint to get blocks harvested by an account

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#250]
*Reported by @evias*

> Add the possibility to add /account/x/blocks as blocks that have been harvested by account x. 

I will submit a proposal for the structure of the endpoint as requested. Then, we can discuss if it is feasible from a technical point of view.

**Comment by Vektrat** [comment]
thanks @dgarcia360

**Comment by dgarcia360** [comment]
Added an implementation proposal here https://github.com/nemtech/catapult-rest/issues/250. Note that I have defined a couple of endpoints, one to retrieve the blocks harvested by an account and a second to get the blocks where an account is set as beneficiary.

Let me know what do you think about the proposed implementation.

**Comment by Vektrat** [comment]
https://github.com/nemtech/nem2-openapi/pull/75

**Comment by Vektrat** [comment]
as mentioned in the openapi repo, the `beneficiary` endpoint implementation will be skipped, delivering just `/account/{accountId}/harvest` with the matching signer
