### ISSUE TITLE
Failure_Namespace_Invalid_Duration thrown instead of Failure_Namespace_Already_Exists

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-rest#252]
on current testnet
ws://api-xym-3-01.us-west-2.nemtech.network:3000/ws

when trying to register a namespace that already exists, `Failure_Namespace_Invalid_Duration ` is thrown instead of `Failure_Namespace_Already_Exists`

![image](https://user-images.githubusercontent.com/36499647/74121326-1689da00-4c02-11ea-9cf7-0d20f8f3c7b9.png)

**Comment by Vektrat** [comment]
i just checked REST against server and everything seems in order

- https://github.com/nemtech/catapult-server/blob/master/plugins/txes/namespace/src/validators/Results.h#L34
- https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/status.js#L77

- https://github.com/nemtech/catapult-server/blob/master/plugins/txes/namespace/src/validators/Results.h#L68
- https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/status.js#L122

maybe server is throwing the wrong error code? @BloodyRookie @gimer @Jaguar0625

**Comment by BloodyRookie** [comment]
@decentralizer, can you paste the namespace id?
@Vectrat, why did you close this issue?

**Comment by decentraliser** [comment]
@BloodyRookie 
84304D4AB17B4CAD

http://explorer-xym.nemtech.network/namespace/84304D4AB17B4CAD

**Comment by Vektrat** [comment]
closed it because in theory it does not belong to REST from what i checked, i believe each issue should belong to its repo, either way it can always be reopened so if you want to make sure first it's fine for me if you want it to remain open

**Comment by BloodyRookie** [comment]
1) You are allowed to register the same root more than one time. The lifetime is extended by the given duration each time you register thr root.
But...
2) The overall lifetime is not allowed to exceed the value *maxNamespaceDuration* from config-network.properties.

In your case, you are violating 2) and thus the transactions is rejected with the correct error message.

**Comment by decentraliser** [comment]
Oh right... sorry about that!
