### ISSUE TITLE
Add endpoint to get blocks where an account is beneficiary

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#253]
Proposed spec: https://github.com/nemtech/nem2-openapi/pull/76

Right now it there is no index in MongoDB to filter by ``beneficaryPublicKey``. It would be possible to add it in the next release @gimer @BloodyRookie @Jaguar0625?

**Comment by BloodyRookie** [comment]
i don't mind addding the index

**Comment by Vektrat** [comment]
> i don't mind addding the index

great, we will be implementing this then when the index is there ^^

**Comment by Vektrat** [comment]
index added, ready to develop

https://github.com/nemtech/catapult-server/commit/0e83889697b835cacf7293d4ff732ded83b76d82
