### ISSUE TITLE
Add REST endpoint for current effective rental fee recommendation

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#254]
Continuation of #98 

Include information about effective rental fees calculated over the period of ``maxDifficultyBlocks``:

* Effective rental fee to register/extend a namespace per block.
* Effective rental fee to create a subnamespace.
* Effective rental fee to create a mosaic.

**Calculation**
This information should be already calculated by catapult-server. If you cannot retrieve it, you can calculate it as follows:

* [Mosaics rental fee](https://nemtech.github.io/concepts/mosaic.html#rental-fee)
* [Namespaces rental fee](https://nemtech.github.io/concepts/namespace.html#namespace-rental-fee)

Example of pseudocode for effectiveRootNamespaceRentalFeePerBlock:

```
/* 1. Get latests maxDifficultyBlocks */
blocks = getBlocks(maxDifficultyBlocks)

/* 2. In case there are zero multipliers, these are replaced by the defaultDynamicFeeMultiplier before the median calculation. */
blocks = blocks.map( block => {
  if (block.feeMultiplier == 0) { block.feeMultiplier = defaultDynamicFeeMultiplier}
  return block;
})

/* 3. Calculate the median network multiplier */
medianNetworkMultiplier = median([ block.feeMultiplier for block in blocks])

/* 4. Multiply the default value set in the configuration by the median network multiplier. */

namespaceRentalEffectiveFee = rootNamespaceRentalFeePerBlock * medianNetworkMultiplier
```

**Comment by Vektrat** [comment]
do you know where in the server would this be available?

**Comment by dgarcia360** [comment]
Not sure where this is stored, but should be calculated for every block @Jaguar0625 @BloodyRookie @gimer  When a namespace registration or mosaic definition transaction is confirmed, the network substracts to the account the ``effectiveRentalFee``, and reflects this action issuing a receipt.

**Comment by Vektrat** [comment]
with progress on the decisions behind #64 we can proceed with this

we will create a new endpoint that provides the missing information from the oringinal endpoint design: the second half with the rental fees info in https://github.com/nemtech/symbol-openapi/pull/55/commits/a09a46251c70116e18c96b5f640866ce424ff0b9, following the pseudocode provided here by david

just like the `/network/properties` endpoint, this will fail if there's any kind of failure trying to parse the config file

endpoint suggestion pending by @dgarcia360 but i expect `/network/fees` or similar

**Comment by dgarcia360** [comment]
The initial thought was to include transaction fees and rental fees under the same endpoint. However, this would become unusable if the REST instance cannot reach catapult-server ``config-network.properties`` file.

For that reason, I propose to organize the fees related endpoints as follows:

* ``/network/fees/rental``: New endpoint #254.
* ``/network/fees/transaction``: Move existing ``/network/fees``.
