### ISSUE TITLE
unconfirmed WS channel is not reporting anything

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#256]
as reported by https://nem2.slack.com/archives/C9YKR0EUX/p1581238937086000

apparently this is happening on _all_ unconfirmed transactions

@planethouki @xembook to keep you on the loop

maybe related to #245

**Comment by Vektrat** [comment]
reports has shown that this might not be a REST issue after all

**Comment by fboucquez** [comment]
I think code and deadline lines need to be swapped

https://github.com/nemtech/catapult-rest/blob/master/rest/src/connection/MessageChannelBuilder.js#L96

Reflecting this server change:

https://github.com/nemtech/catapult-server/commit/bc4185117de1bf2c15d9797aec7c57f20175b7f2

**Comment by Vektrat** [comment]
confirmed server issue
