### ISSUE TITLE
Need clarification about mosaics

### ISSUE THREAD

**Issue by QuantumMechanics** [nemtech/catapult-rest#26]
Hi,

I don't understand why the mosaics of the nemesis accounts have different ids from the mosaics received in the first transaction.

Account has mosaics with ids _[3555157025, 1492784701]_ and _[3375658510, 1046278526]_

![c_mosaics_2](https://user-images.githubusercontent.com/8740532/56984985-9f5dea80-6b87-11e9-9349-69229f9ab9b1.png)

Transaction has mosaics _[3294802500, 2243684972]_ and _[3084986652, 2484246962]_ 

![c_mosaics_1](https://user-images.githubusercontent.com/8740532/56984984-9ec55400-6b87-11e9-9ac9-eee0be9376f8.png)

Could you clarify ?

Thanks

**Comment by Vektrat** [comment]
I don't think this has anything to do specifically with the REST server since both schemas are using the same mosaics parser, I suggest you ask in slack

**Comment by QuantumMechanics** [comment]
Yes sorry, already asked on slack few weeks ago but got no more details, will try to bump
