### ISSUE TITLE
Invalid error message when metadata doesn't exist

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#267]
I'm getting the following message when the metadata doesn't exist.

![image](https://user-images.githubusercontent.com/5390558/74833679-b9281400-52f8-11ea-9117-16bd0ec085f8.png)

I think the invalid value is the sender. 

This is current master

**Comment by martinayora** [comment]
I think this is duplicate of #206.

**Comment by fboucquez** [comment]
Yes, duplicated, I thought it was fixed and back again
