### ISSUE TITLE
Receipt - AddressResolutionStatement resolved value has wrong format.

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#27]
`resolved` value should be encoded in `Hex` format.

See. [http://c2.nem.ninja:3000/block/19/receipts](http://c2.nem.ninja:3000/block/19/receipts)

```
{"height":[19,0],
"unresolved":"91E4EDFC6EE000CEFF00000000000000000000000000000000",
"resolutionEntries":[
      {"source":{"primaryId":3,"secondaryId":0},
       "resolved":"kHiyJYtPHGBhINoJIjut3USNYP0cq7DJnw=="
      }
]
}
```

**Comment by Vektrat** [comment]
@gimer @BloodyRookie was `entries` renamed to `resolutionEntries`?

**Comment by BloodyRookie** [comment]
i don't remember renaming it, maybe it was like this from the beginning?

**Comment by Vektrat** [comment]
nope, https://phab.nem.ninja/P210 but nevermind, updated ^^
