### ISSUE TITLE
Server error on NetworkProperties

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#280]
```{
    "code": "InvalidArgument",
    "message": "there was an error reading the network properties file"
}
```

Running on the local bootstrap server with the latest rest master

**Comment by Vektrat** [comment]
how are you running the REST server? detached or within the bootstrap? what command exactly if detached?

@kaiyzen did you get by the issue you had?

**Comment by Vektrat** [comment]
btw i'm almost certain this is not a REST issue, more of a deploy/file issue as the error specifies

**Comment by rg911** [comment]
Probably the config files location not setup in the rest.json. I will digger it out

**Comment by fboucquez** [comment]
you need to update your rest.json file. Add `propertiesFilePath` to the network section

````
{
  "network": {
    "name": "publicTest",
    "description": "catapult development network",
    "propertiesFilePath": "/home/fernando/develop/workspace-nem/catapult-service-bootstrap/build/catapult-config/api-node-0/userconfig/resources/config-network.properties"
  },
...
````
@kaiyzen, can we add the path to the `rest.json.mt` template? How can we get the bootstrap folder absolute path?

**Comment by Vektrat** [comment]
this setting is optional, this is why there's no other errors, otherwise we'd most likely throw on startup

**Comment by fboucquez** [comment]
what about logging a warning on boot?
