### ISSUE TITLE
If there is no outgoing transaction, should the public key of AccountDTO return null

### ISSUE THREAD

**Issue by daoka** [nemtech/catapult-rest#3]
When get account (that is no outgoing transaction) info by Catapult rest api `/account/:accountId` , public key return `0000000000000000000000000000000000000000000000000000000000000000`
Using this PublicKey will be the address 'SAXQUTQQNS6JEJG7PLC6FRVJ2USS44GLMXG4DOF2' when MIJIN_TEST.

I think there is a concern that you get the public key from the address in the API and accidentally create an aggregate transaction using this public key.

So, I think that should return null like NIS1 when returning the public key of an account with no outgoing transaction in the API.

**Comment by aleixmorgadas** [comment]
@BloodyRookie , the case described could be a problem, since `00....0` public key is a valid key. The API return a `undefined` value for the public key, is this a change at API level or MongoDB level?

**Comment by Vektrat** [comment]
same happens with `linkedAccountKey`

this change should comefrom core level because at REST side right now there's no way to know if the key is a valid (0x00...00) key, or just marking it as undefined
