### ISSUE TITLE
ActivityBucket open api spec inconsistency

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#302]
Hi guys, unsure if this is a rest or an open API bug.

[ActivityBucketDTO.yml](https://github.com/nemtech/symbol-openapi/blob/master/spec/core/account/schemas/ActivityBucketDTO.yml) specifies that `totalFeesPaid` and `rawScore` are number, rest is returning them as string numbers:

http://api-01.us-west-1.symboldev.network:3000/account/TAI4NEL4SBQDSPY2XKMPIGOC53UALIXJ5WHRJVQZ

![image](https://user-images.githubusercontent.com/5390558/79815178-6699c100-8356-11ea-80d7-1ca298657c44.png)

Should rest return an int number or open API spec change it to string number (Uint64)? @Vektrat @dgarcia360

**Comment by Vektrat** [comment]
in REST we have them listed as `uint64`, and in mongodb they are uint64, so probably openapi needs to change

**Comment by dgarcia360** [comment]
This is a OpenAPI spec issue, it was docuemnted after ActivityBucketDTO was implemented. A fix has been applied here https://github.com/nemtech/symbol-openapi/commit/780dae70b86773fc2b3f03f75a39e46b7eca53fc
