### ISSUE TITLE
Notification from unconfirmedRemoved, partialRemoved and cosignature will be received by all registered address with the same web socket connection

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#309]
1. Expected behavior and actual behavior.
If multiple accounts register multiple accounts to listen to cosignature using one listener. They should only get notify for transactions that have their address.
2. Steps to reproduce the problem.
Register multiple accounts to listen to cosignature using one listener.

Does not filter using the user address.

```
    /**
     * Returns an observable stream of {@link CosignatureSignedTransaction} for specific address.
     * Each time a cosigner signs a transaction the address initialized,
     * it emits a new message with the cosignatory signed transaction in the even stream.
     *
     * @param address address we listen when a cosignatory is added to some transaction address sent
     * @return an observable stream of {@link CosignatureSignedTransaction}
     */
    public cosignatureAdded(address: Address): Observable<CosignatureSignedTransaction> {
        this.subscribeTo(`cosignature/${address.plain()}`);
        return this.messageSubject.asObservable().pipe(
            filter((_) => _.channelName.toUpperCase() === ListenerChannelName.cosignature.toUpperCase()),
            filter((_) => _.message instanceof CosignatureSignedTransaction),
            map((_) => _.message as CosignatureSignedTransaction),
        );
    }
```

Basically when multiple subscriptions set up in one listener object, without knowing the uri / channel name (e.g. consignatureAdd/{address}) multiple notifications will be received. Discussed internally, and would like rest to have a look.

Ref https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/542

**Comment by Vektrat** [comment]
note to myself: the problem here is that a WS is being reused for multiple subscriptions, and when data is received, the client does not know to which subscription it belonged to, since there's no extra feedback on what matched exactly

**Comment by Vektrat** [comment]
implementing this will make the less than ideal implementation of https://github.com/nemtech/catapult-rest/pull/169 redundant, though i think it still makes sense to return the address within the payload, it would not be needed anymore

**Comment by Vektrat** [comment]
> implementing this will make the less than ideal implementation of #169 redundant, though i think it still makes sense to return the address within the payload, it would not be needed anymore

will definitely drop this, because it does not make sense to have the address within the tx status

**Comment by Vektrat** [comment]
thinking of wrapping (all) WS responses like this:

```yaml
{
    "topic": "confirmedAdded/TDS44G6KUHO7MODUB6E6WVJOK277QY65XCBJX5Y",
    "data": {
        "transaction": { "..." }
    }
}
```

the only alternative i can think of is the following, but i see two issues with it:
- `topic` seems a bit out of place
- you probably want to reuse the transaction DTO here ( https://github.com/nemtech/symbol-openapi/blob/main/spec/core/transaction/schemas/TransactionInfoDTO.yml ), which would involve having (already existing) fields that would never appear in the websockets, and having an extra `topic` field that would never appear in API results - there should be two DTOs for this case (i still think we should have different DTOs for WS and API anyway, but this is minor atm) - with the previous solution you can keep reusing DTOs, and have a WS wrapper like with the pagination, and even if we duplicated DTOs at some point, the wrapper would be fine

```yaml
{
    "topic": "confirmedAdded/TDS44G6KUHO7MODUB6E6WVJOK277QY65XCBJX5Y",
    "transaction": { "..." }
}
```

**Comment by fboucquez** [comment]
I'm keen on having the wrapper with information about the connection. I prefer the first example. It would be something like:
```
{
    "topic": "the topic uri",
    "data": <any of TransactionInfoDTO | BlockInfoDto | String>
}
```

Topic uri like, `"confirmedAdded/TDS44G6KUHO7MODUB6E6WVJOK277QY65XCBJX5Y"`, 
`"partialRemoved/TDS44G6KUHO7MODUB6E6WVJOK277QY65XCBJX5Y"` or `"block"`
