### ISSUE TITLE
Transaction status code needs to be updated with the new codes for 9.5.1

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-rest#328]
New errors were added for the new transaction. One such error is Failure_Core_Link_Already_Exist but there are others.

https://github.com/nemtech/catapult-rest/blob/9cb5d4d1aa2cd10ba0f7d78bcadaf191b7b93d6a/catapult-sdk/src/model/status.js#L24

{"hash":"61D3415802FEE63086E95D0260A9B000CB6DA594A15FA65BB535DFD36847649F","code":"unknown status 0x80430066","deadline":"16508338905","group":"failed"}

catapult_server0001.log:2020-05-19 23:38:59.580589 0x00007fc445ffb700: <warning> (chain::UtUpdater.cpp@160) dropping transaction 61D3415802FEE63086E95D0260A9B000CB6DA594A15FA65BB535DFD36847649F: Failure_Core_Link_Already_Exists
catapult_server0001.log:2020-05-19 23:38:59.586438 0x00007fc445ffb700: <warning> (subscribers::SubscriptionManager.cpp@101) rejected tx 61D3415802FEE63086E95D0260A9B000CB6DA594A15FA65BB535DFD36847649F due to result Failure_Core_Link_Already_Exists (deadline 16508338905)

**Comment by Vektrat** [comment]
fixed in https://github.com/nemtech/catapult-rest/commit/e3675320be8dcab4105daba9bea212896447a3a3

**Comment by dgarcia360** [comment]
@Vektrat The update does not look complete, @Wayonb reported that there are new types like "Failure_Core_Link_Already_Exists" and this error was not added in https://github.com/nemtech/catapult-rest/commit/e3675320be8dcab4105daba9bea212896447a3a3

**Comment by Vektrat** [comment]
> @Vektrat The update does not look complete, @Wayonb reported that there are new types like "Failure_Core_Link_Already_Exists" and this error was not added in [e367532](https://github.com/nemtech/catapult-rest/commit/e3675320be8dcab4105daba9bea212896447a3a3)

oops i screwed up the names ^^ will update and force update the branch

**Comment by Vektrat** [comment]
https://github.com/nemtech/catapult-rest/commit/1aeac3f57a13105d1e134e22c9be98868f21d973 done
