### ISSUE TITLE
Invalid /blocks/:height/transaction/:hash/merkle path

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#360]
There is a mismatch between open API spec (`transactions` plural) and Rest (`transaction` singular).  Is it a Rest or an open API issue?

http://localhost:3000/blocks/1/transaction/EB19C8393558AEBF37DC992ABFEF9B80448B89CD27E27596C4581DD595C33373/merkle 

http://localhost:3000/blocks/1/transactions/EB19C8393558AEBF37DC992ABFEF9B80448B89CD27E27596C4581DD595C33373/merkle

@Vektrat @dgarcia360 @rg911 

https://github.com/nemtech/symbol-openapi/blob/master/spec/routes.yml#L16
https://github.com/nemtech/catapult-rest/blob/master/rest/src/routes/blockRoutes.js#L60

**Comment by Vektrat** [comment]
it has to be plural, we will update tomorrow, you can assume it'll be plural
