### ISSUE TITLE
WS listener transaction id is not returned

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#364]

**Comment by fboucquez** [comment]
I'm announcing an aggregate transaction with a namespace registration and this is the payload received by the listener:

```
{
   "meta":{
      "channelName":"confirmedAdded",
      "hash":"735B7DFDD142D0DF858EB3C2796C3568785B609FACD40D69F1D19C8768311839",
      "height":"12",
      "merkleComponentHash":"735B7DFDD142D0DF858EB3C2796C3568785B609FACD40D69F1D19C8768311839"
   },
   "transaction":{
      "aggregateTransactionHeader_Reserved1":0,
      "deadline":"18491565192",
      "entityBody_Reserved1":0,
      "maxFee":"1000000",
      "network":152,
      "signature":"A546F2639580370ED8AAFDF279621E3669FA425DDE84D8FDA3BB1CA0840A5DAF32B963BB3860DF0194E6AD139DFBCB8DEEB894C47880A8CC1E727AF58CA98D0D",
      "signerPublicKey":"500A35B60AE3BC64344431275A60113F325A0CCD3A9CEE3A5AF7000566D03B03",
      "transactions":[
         {
            "transaction":{
               "duration":"100",
               "embeddedTransactionHeader_Reserved1":0,
               "entityBody_Reserved1":0,
               "id":"BC4187CFBE19E97F",
               "name":"multisig-account",
               "network":152,
               "registrationType":0,
               "signerPublicKey":"500A35B60AE3BC64344431275A60113F325A0CCD3A9CEE3A5AF7000566D03B03",
               "type":16718,
               "version":1
            }
         }
      ],
      "transactionsHash":"F2FAE134F28388F3C0665E10DB98D138F0467DF114232AB506FE5B1C12DF6EEA",
      "type":16705,
      "verifiableEntityHeader_Reserved1":0,
      "version":1
   }
}
```

The embedded transaction doesn't have meta. 
What's the top-level transactionsHash?

**Comment by Vektrat** [comment]
1. we don't modify WS data at all, so if something is missing this is a question for core probably - plus nothing has changed on WS end with latest updates regarding this if i believe
2. transactionsHash or transaction hash? because i believe transactionsHash is a block field
3. the embedded transaction has no meta because it is put within it's top-level/parent transaction, are you referring to the parent transaction hash? because it is in the meta.hash

**Comment by Vektrat** [comment]
i just saw question was edited:
- same as before with regards to 1, so nothing much we can do
- why do you need meta when you have parent info?

**Comment by fboucquez** [comment]
It's ok, I got confused with the extra hash in the aggregate. It's ok if meta is not in the embedded

**Comment by Wayonb** [comment]
@Vektrat Looking at the json payload above from @fboucquez , Rest should also be removing the reserved fields.

1.  Catbuffer does not returned the reserved fields
2. Reserved fields are extra bytes(overhead) that are not used by the client. This can add up esp for aggregate transactions.

Reserve fields.
      "aggregateTransactionHeader_Reserved1":0,
      "embeddedTransactionHeader_Reserved1":0,
     "entityBody_Reserved1":0,
      "verifiableEntityHeader_Reserved1":0,
