### ISSUE TITLE
TransactionSearch group filter doesn't not work

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#365]
https://github.com/nemtech/symbol-openapi/blob/dca2bd211ec78662dbaa6a0c5a2eb7f6b4894607/spec/core/transaction/routes/searchTransactions.yml#L14

Looks like rest is using `state`

**Comment by fboucquez** [comment]
Is there a way of joining different collections in Mongo and sort out the aggregated table?

**Comment by Vektrat** [comment]
technically yes, practically no, we have already looked into this and it's not feasible
