### ISSUE TITLE
getTransaction by ids 500 error

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#393]
when sending nonsense data  

Error: {"statusCode":500,"statusMessage":"Internal Server Error","body":"{\"code\":\"Internal\",\"message\":\"Cannot read property 'length' of null\"}"}

**Comment by Vektrat** [comment]
violtation of precondition results in unexpected behaviour, this is normal

i agree with the fact of not liking the server throwing uncontrolled 500 errors but overall this needs to be reviewed and i don't think it is worth it to have a single issue for this case
