### ISSUE TITLE
Heartbeat and status api call missing

### ISSUE THREAD

**Issue by gimyboya** [nemtech/catapult-rest#4]
The title says it all. the current implementation doesn't have `/status` or `/heartbeat` api call

**Comment by Vektrat** [comment]
@dgarcia360 @evias @kaiyzen  do you think this is needed? i understand some orchestrators require such endpoints to manage extra node activation, does it make sense to have a specific call for this? or is `/node/info` useful for example?

what information would be expect from a status/heartbeat call (assuming we would just be adding one call)?

it shouldn't be a problem adding this, i just want to make sure we don't bloat the server with redundant endpoints

**Comment by jontey** [comment]
Heartbeat should check if the connection to the mongoDB is valid as well as to the API node endpoint.

However with the current implementation the rest gateway would crash on start if either mongoDB or API node is not ready. So right now our solution is to keep restarting the service if it crashes until it comes up.
