### ISSUE TITLE
Add route/module for p2p endpoint(s)

### ISSUE THREAD

**Issue by evias** [nemtech/catapult-rest#40]
I am facing an issue that currently I don't seem to be able to **find out peer neighborhood and peer lists** from a connection through catapult-rest.

I have come to know that `catapult-server` comes with a P2P API on port 8000, but our SDK currently doesn't provide with an integration of that gateway.

Two possibilities arrise here as we may implement this in the SDK connecting through port 8000 (not optimal.) or catapult-rest could provide with following proposed endpoint:

- `/peers`: Get the list of neighbours for a node

This can, of course, be named differently if you have better suggestions.

**Comment by Vektrat** [comment]
should this be provided by REST? @Jaguar0625 @BloodyRookie @gimer

**Comment by Vektrat** [comment]
this was picked up by @evias 's team and core devs are working along them to reach a solution, i don't know if REST will be involved in the outcome, so i'll keep this open for a while
