### ISSUE TITLE
Offset returning empty pages

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#420]
I'm testing offset in different endpoints and it seems like the pages are always empty when it's provided:

One example is completed transactions:

![image](https://user-images.githubusercontent.com/5390558/87851794-83508100-c8d2-11ea-942d-eef1c51cd48f.png)

Once I copy any id into an offset param, I get empty results

![image](https://user-images.githubusercontent.com/5390558/87851829-bdba1e00-c8d2-11ea-92f7-3a018f429f4a.png)

I can replicate this with at least block, metadata, namespaces.

This is from current master.

**Comment by Vektrat** [comment]
Fixed in https://github.com/nemtech/catapult-rest/pull/428

**Comment by fboucquez** [comment]
Thanks, it looks good.
