### ISSUE TITLE
Namespace names endpoint return 409 Conflict status

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/catapult-rest#426]
REST version: v1.1.3

http://api-01.us-west-1.096x.symboldev.network:3000/namespace/FFEB6C9A09F9173E

I was not able get the namespace names from this namespaceId `FFEB6C9A09F9173E`, other id seem working well.

[POST]  http://api-01.us-west-1.096x.symboldev.network:3000/namespace/names

```
Body
{
    "namespaceIds": ["FFEB6C9A09F9173E"]
}
```

**Comment by Vektrat** [comment]
we are on it but unlike other bugs this one is a little weird so it might not have an immediate fix

**Comment by AnthonyLaw** [comment]
@Vektrat No problem, thanks 👍

**Comment by Vektrat** [comment]
can you give us more information on the characteristics of this specific `namespaceId`? with the info provided it is impossible for us to reproduce this, and we don't have direct access to the node data to check this hands on

**Comment by Vektrat** [comment]
also, not sure if this will persist (probably yes), but the endpoints you are calling are the old ones (and right ones considering you are still running 1.1.3 REST) -it'd be great to check this after updating to 1.2.0 REST which has updated namespaces endpoints, because right now i don't even know if you are still running the fork, or traces of it

**Comment by evias** [comment]
the namespaces endpoint is now at /namespace**s*/names.

**Comment by AnthonyLaw** [comment]
@Vektrat I had found the detail for this Namespace.

http://explorer-96x.symboldev.network/transaction/2B710785E1E5F8A9D005DFF95D22BB0E13B0C4DE78C053F412C7613FFDBCA74D

@evias i will try on 1.2 REST and test.

**Comment by Vektrat** [comment]
did you manage to try this with 1.2?

**Comment by AnthonyLaw** [comment]
yes, latest endpoint using the latest REST

http://172.104.61.28:3000/

still hit the same error.
