### ISSUE TITLE
please refactor key or address parameter parsing 

### ISSUE THREAD

**Issue by Jaguar0625** [nemtech/catapult-rest#43]
const getParams = req => {
      if (req.params.publicKeys && req.params.addresses)
        throw errors.createInvalidArgumentError('publicKeys and addresses cannot both be provided');

      const idOptions = Array.isArray(req.params.publicKeys)
        ? { keyName: 'publicKeys', parserName: 'publicKey', type: AccountType.publicKey }
        : { keyName: 'addresses', parserName: 'address', type: AccountType.address };

      const accountIds = routeUtils.parseArgumentAsArray(req.params, idOptions.keyName, idOptions.parserName);

**Comment by Vektrat** [comment]
closing because this is slowly being removed from the API with the endpoint reviews
