### ISSUE TITLE
Review Docker/bootstrap PR

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#434]
#425 

estimation: 4h

**Comment by Pow1404** [comment]
What is required to remove the blocker here?

**Comment by Vektrat** [comment]
> What is required to remove the blocker here?

https://github.com/nemtech/catapult-rest/pull/425#issuecomment-664840404

https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1596003360182600

**Comment by fboucquez** [comment]
Thanks for merging the PR.

As a reference, the tags are here

https://hub.docker.com/r/symbolplatform/symbol-rest/tags
