### ISSUE TITLE
Decide schema upgrade

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#435]
estimation: 2 days

**Comment by Vektrat** [comment]
after [discussion](https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1594887989082900) with jaguar we will proceed with going with the original idea (doing it within REST), because we see there are more drawbacks than benefits, and having it in catbuffer would only help transactions (not all the other mongodb schemas), plus catbuffer transactions are not always strictly equal to those of mongo

**Comment by Pow1404** [comment]
Will you now create a new task/ set of tasks to reflect the work to upgrade schemas and mark in backlog as enhancements? Once tasks created can you add more detail on what the changes will be? @Vektrat

**Comment by Vektrat** [comment]
> Will you now create a new task/ set of tasks to reflect the work to upgrade schemas and mark in backlog as enhancements? Once tasks created can you add more detail on what the changes will be? @Vektrat

we were obviously going to do that, yes
