### ISSUE TITLE
Add endpoint to list finalized blocks

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#457]
spec: https://github.com/nemtech/symbol-openapi/pull/194

**Comment by Vektrat** [comment]
- https://github.com/nemtech/catapult-server/blob/main/extensions/mongo/src/MongoFinalizationStorage.cpp
- https://github.com/nemtech/catapult-server/blob/main/extensions/mongo/src/mappers/BlockMapper.cpp#L104

the protagonist of this endpoint will be the `point` rather than `height`, because:
- heights have gaps: due to how the procedure works, if block X is finalized, all blocks < X are also finalized (i.e. notification block 100 is finalized, next notification block 150 is finalized)
- finalization points are unique and increase sequentially
- heights are not unique: there can also be finalization rounds (points) where network is partitioned, so nothing will be finalized, that’s why you could see duplicate heights

note: the entity height is the height of the finalized block, not the height at which finalization happened (we have the points for this)

**Comment by Vektrat** [comment]
thinking of adding `latestFinalizedHeight` to `/chain/info`

@AnthonyLaw how useful would be this endpoint from a client perspective? i mean `/finalizedBlocks`, sounds pretty useless to me but 🤷‍♂️

**Comment by AnthonyLaw** [comment]
Hi @Vektrat 
For client prespective, user/exchanger just need to know the `Finalized` status of the block.

I believe `latestFinalizedHeight` would be helpful for compare the the block and proof/show the `Finalized` status.

Example in Explorer i will do

1. all blocks < `latestFinalizedHeight`, marked block was finalized.

![image](https://user-images.githubusercontent.com/5649156/91081465-c47a4480-e679-11ea-8ef8-f03bbb4b6b5c.png)


2. all blocks > `latestFinalizedHeight`, block pending for finalized.
![image](https://user-images.githubusercontent.com/5649156/91081983-8df0f980-e67a-11ea-85b5-197ce7ff6732.png)

**Comment by AnthonyLaw** [comment]
For the endpoint `/finalizedBlocks` is not really useful, in my opinions. 

because if we can get `latestFinalizedHeight`,  and use it to query blockInfo from `SearchBlocks` endpoint.

**Comment by fboucquez** [comment]
Yeap, `latestFinalizedHeight` and maybe a `finalizationPoint` in `block` if really necessary would be perfect

**Comment by Vektrat** [comment]
> For the endpoint `/finalizedBlocks` is not really useful, in my opinions.
> because if we can get `latestFinalizedHeight`, and use it to query blockInfo from `SearchBlocks` endpoint.

ok we will drop work on the `list` endpoint for now, i'll leave the spec/issue open in case we need it in a month, else, i will close this and openapi as well
