### ISSUE TITLE
Consider adding (transfer) transaction filters: fromMosaicAmount toMosaicAmount

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#470]
https://forum.nem.io/t/symbol-wallet-features-requests-search-sort-receipts/25655

**Comment by Vektrat** [comment]
might require an extra task: add option to filter transfer transactions involving a specific mosaicId (`transferMosaic`)

_this_ issues filters suggestion: `fromTransferAmount` and `toTransferAmount`

**Comment by Vektrat** [comment]
@evias @segfaultxavi what do you think of this?

**Comment by segfaultxavi** [comment]
The ability to filter by transfer amount seems useful, of course.

I agree you probably first need to be able to filter by mosaicId (because you can have different "currencies" in the same network, right?).
I also agree filtered queries then will require providing `transferMosaicId` along with `from` and `toTransferAmount`. I am no expert in REST, but this extra parameter seems cumbersome. Is there a more comfortable REST way of doing this?

The forum post also requests filtering by date. Are we planning to support that filter too?

**Comment by Vektrat** [comment]
it is true that the params are a bit cumbersome, after all they are related and even exclusive (`height`, `fromHeight`, `toHeight`), the problem with this is that alternatives are even worse than this (which at least is readable and simple, other than increasing the number of params), and nothing is standarized

you can define a custom object, but it would be ugly, and require yet an extra "protocol" to be understood between clients and server - it could be as simple as `amount=5-100` or more complex such as `amount={ "ge": 5, "le": 100 }`, but every solution has specific caveats (other than the ones already mentioned).

For example, for the first one, if a single amount was provided (exact match), the structure would be changing already (unless the user did `amount=5-5`), and also, right now amount is a number, which is naturally correct, if we made this, amount would be a string with a project-specific format that required definition. For the second one well... we can enrich the object so that providing a single value (exact match) wouldn't be an issue anymore, but it means more complexity and even more definition, not to mention it is even uglier


with regards to your last question, check this: https://github.com/nemtech/symbol-openapi/pull/205#issuecomment-689429171 (also feel free to "fix" the PR with your comments if you want ^^)

**Comment by segfaultxavi** [comment]
OK, understood, thanks! I was just curious to know if there was any standardized way of doing this.

You proposal looks good to me!

**Comment by Vektrat** [comment]
blocked by #483
