### ISSUE TITLE
Endpoint not returns all the embedded aggregate transactions (&embedded=true)

### ISSUE THREAD

**Issue by Vladimir7280** [nemtech/catapult-rest#498]
Endpoint not returns all the embedded aggregate transactions

http://api-01.ap-northeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed?address=TDEROLO7NEKETJRPPSIFVXST26WZSVAYVCPUR7A&type=16705&type=16973&embedded=true

only top-level transactions  are returned.

{
"data": [
{
"meta": {
"height": "39190",
"hash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"merkleComponentHash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"index": 0
},
"transaction": {
"size": 312,
"signature": "F1FCAB693709E1E3F495F27D6977422CEB839AD62535A1DB780F2F56E1AEA68A6F27271EB4A6D75A46750860846D7037199E74482CFB606A484ABA2E44AA0E0B",
"signerPublicKey": "EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC",
"version": 1,
"network": 152,
"type": 16705,
"maxFee": "312000",
"deadline": "28812363542",
"transactionsHash": "F010B2A87F66A19DC1BE9E220D15F20032A84D73D43458353384774F97725CA1",
"cosignatures": [ ]
},
"id": "5F802CFBACD4D71BB267923C"
}
],
"pagination": {
"pageNumber": 1,
"pageSize": 20
}
}

**Comment by Vektrat** [comment]
the problem is that you are filtering by the aggregate type `&type=16973` which is the type of parent transactions, so it's normal that the embedded are not returned

**Comment by Vladimir7280** [comment]
> the problem is that you are filtering by the aggregate type `&type=16973` which is the type of parent transactions, so it's normal that the embedded are not returned

without a filter (& type), the result is not changed.

**Comment by Vektrat** [comment]
> > the problem is that you are filtering by the aggregate type `&type=16973` which is the type of parent transactions, so it's normal that the embedded are not returned
> 
> without a filter (& type), the result is not changed.

without a type filter the result is of 15 transactions, though it is true that none of those is embedded
maybe you are encountering this bug? https://github.com/nemtech/catapult-rest/issues/433

**Comment by Vladimir7280** [comment]
> > > the problem is that you are filtering by the aggregate type `&type=16973` which is the type of parent transactions, so it's normal that the embedded are not returned
> > 
> > 
> > without a filter (& type), the result is not changed.
> 
> without a type filter the result is of 15 transactions, though it is true that none of those is embedded
> maybe you are encountering this bug? #433
**request**
http://api-01.ap-northeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed?address=TDEROLO7NEKETJRPPSIFVXST26WZSVAYVCPUR7A&height=39190&embedded=true

**response**
{
"data": [
{
"meta": {
"height": "39190",
"hash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"merkleComponentHash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"index": 0
},
"transaction": {
"size": 312,
"signature": "F1FCAB693709E1E3F495F27D6977422CEB839AD62535A1DB780F2F56E1AEA68A6F27271EB4A6D75A46750860846D7037199E74482CFB606A484ABA2E44AA0E0B",
"signerPublicKey": "EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC",
"version": 1,
"network": 152,
"type": 16705,
"maxFee": "312000",
"deadline": "28812363542",
"transactionsHash": "F010B2A87F66A19DC1BE9E220D15F20032A84D73D43458353384774F97725CA1",
"cosignatures": [ ]
},
"id": "5F802CFBACD4D71BB267923C"
}
],
"pagination": {
"pageNumber": 1,
"pageSize": 20
}
}

if the **request** for this transaction

http://api-01.ap-northeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed/7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23

**response** shows embedded transactions
{
"meta": {
"height": "39190",
"hash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"merkleComponentHash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"index": 0
},
"transaction": {
"size": 312,
"signature": "F1FCAB693709E1E3F495F27D6977422CEB839AD62535A1DB780F2F56E1AEA68A6F27271EB4A6D75A46750860846D7037199E74482CFB606A484ABA2E44AA0E0B",
"signerPublicKey": "EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC",
"version": 1,
"network": 152,
"type": 16705,
"maxFee": "312000",
"deadline": "28812363542",
"transactionsHash": "F010B2A87F66A19DC1BE9E220D15F20032A84D73D43458353384774F97725CA1",
"cosignatures": [ ],
"transactions": [
{
"meta": {
"height": "39190",
"aggregateHash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"aggregateId": "5F802CFBACD4D71BB267923C",
"index": 0
},
"transaction": {
"signerPublicKey": "EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC",
"version": 1,
"network": 152,
"type": 16717,
"nonce": -1308811012,
"id": "33378B6F2D19B163",
"flags": 2,
"divisibility": 5,
"duration": "0"
},
"id": "5F802CFBACD4D71BB267923D"
},
{
"meta": {
"height": "39190",
"aggregateHash": "7B1C15BAB35C1385408AE65CFE70CB5B138A384B567F4A978922E95755676B23",
"aggregateId": "5F802CFBACD4D71BB267923C",
"index": 1
},
"transaction": {
"signerPublicKey": "EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC",
"version": 1,
"network": 152,
"type": 16973,
"mosaicId": "33378B6F2D19B163",
"action": 1,
"delta": "500000000"
},
"id": "5F802CFBACD4D71BB267923E"
}
]
},
"id": "5F802CFBACD4D71BB267923C"
}

**Comment by Vektrat** [comment]
i believe you are encountering bug #433 where address cannot be used to get embedded transactions, in your case it does not affect you too much because you can try with PK instead, the problem would be for recipientAddresss - i'll await confirmation

http://api-01.ap-northeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed?signerPublicKey=EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC&height=39190&embedded=true

**Comment by Vladimir7280** [comment]
> i believe you are encountering bug #433 where address cannot be used to get embedded transactions, in your case it does not affect you too much because you can try with PK instead, the problem would be for recipientAddresss - i'll await confirmation
> 
> http://api-01.ap-northeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed?signerPublicKey=EFD82781C2C65F0074D59DDC33B38BC5BE68B8B9243A3B234256807F4DA56AAC&height=39190&embedded=true


I confirm. filter signerPublicKey=   is Ok.

Many thanks
