### ISSUE TITLE
How to config the CORS

### ISSUE THREAD

**Issue by thomas-tran** [nemtech/catapult-rest#5]
I am using the javascript SDK to announce transaction to the network. However, I am getting the error on the browse 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I am just wondering how to set the Access Control Allow Origin for the rest server.

Thanks

**Comment by Vektrat** [comment]
hi, notice that a PR addressing this feature was recently pushed, check the updated `rest.json` config file to see configuration details
