### ISSUE TITLE
Rest should not return namespaces that are expired.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-rest#515]
Currently, REST only returns active namespaces.  This `active` field really means the latest namespace entry.  REST needs to do additional checks on the end height for the namespace and return only the namespace that is still valid(i.e. end height > blockchain height)

https://github.com/nemtech/catapult-rest/blob/15922d068158aa49a6e62feb4a2a6681e8762665/rest/src/plugins/namespace/NamespaceDb.js#L72

This is related to the server issue below.

https://github.com/nemtech/catapult-server/issues/105#issue-732819128

**Comment by fboucquez** [comment]
Ok, I got this. But currently, Rest returns expired mosaics. Should it be consistent? @Wayonb @Jaguar0625

**Comment by fboucquez** [comment]
This has been fixed until the next version where meta.active will be renamed
