### ISSUE TITLE
It's valid duplicated namespace return from a mosaic?

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/catapult-rest#530]
MosaicId: `76978EB3C7AEF573`

![image](https://user-images.githubusercontent.com/5649156/99521465-6ab2bd80-29cf-11eb-856b-7cbc92605158.png)

**Comment by fboucquez** [comment]
I cannot replicate it. I've tried to search for a similar issue in testnet but no luck (by searching all mosaics and all their aliases). 

I could add a fix about how the "names" list is creating (removing duplicated) but I'm not sure to add it just in case we are hading a duplicated item in the db.

**Comment by AnthonyLaw** [comment]
it was found in the old network, I'm not sure about the new network.

**Comment by rg911** [comment]
This is probably related to server 148 bug
