### ISSUE TITLE
/node/storage causes a high load.

### ISSUE THREAD

**Issue by xembook** [nemtech/catapult-rest#555]
The load when using /node/storage is very high, and REST stops responding after just a few requests on TEST_NET. 
This may not be a problem right now(after MAIN_NET launch), but you may need to take measures such as using the cache.

**Comment by fboucquez** [comment]
It seems like countDocuments() calls from storage info are slow when we have a lot of documents. countDocuments() seems to be linear so it won't scale well.

https://github.com/nemtech/catapult-rest/blob/main/rest/src/db/CatapultDb.js#L168

https://stackoverflow.com/questions/57801753/mongodb-countdocuments-is-slow-when-result-set-is-large-even-if-index-is-used

What about using estimatedDocumentCount() for these collections (at least the transactions one).  We would need to update the open api either adding a description telling a fied is a estimate or changing the name of the file (like estimatedNumTransactions)

**Comment by gimer** [comment]
I'm guessing this can be closed? @fboucquez @rg911 ?
