### ISSUE TITLE
Problem with experimental node

### ISSUE THREAD

**Issue by cryptoBeliever** [nemtech/catapult-rest#578]
When calling /network/fees/transaction on the experimental node (pre-mainnet) I'm getting 500:

http://api.experimental.symboldev.network:3000/network/fees/transaction

{
"code": "Internal",
"message": "The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined"
}

**Comment by fboucquez** [comment]
I believe this is yours @gimer 

Rest needs access to both the config-network.properties and config-node.properties. Do you have this in your rest.json configuration?

  apiNode: {
    ......
    networkPropertyFilePath: '<api config path>/config-network.properties',
    nodePropertyFilePath: '<api config path>/config-node.properties'
  },

**Comment by cryptoBeliever** [comment]
Fixed.
