### ISSUE TITLE
Allow in the endpoint of receive transactions given an account to be sorted by height ASC and DESC.

### ISSUE THREAD

**Issue by aleixmorgadas** [nemtech/catapult-rest#7]
In the endpoints

- http://localhost:3000/account/{publicKey}/transactions
- http://localhost:3000/account/{publicKey}/transactions/outgoing
- http://localhost:3000/account/{publicKey}/transactions/incoming

should be a query param to ask the transactions ordered by `block height` ascendant or descendant.

### Motivation

The library [nonfungible-asset](https://github.com/aleixmorgadas/nem2-nonfungible-asset/) will benefit due to be able to read the transactions in batches instead of loading all transactions in memory and then reverse the order.

**Comment by Vektrat** [comment]
Coming soon from foundation development
