### ISSUE TITLE
websocket - 'confirmed' channel not responding on MosaicDefinitionTransaction

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#72]
- Noticed that when announcing a `MosaicDefinitionTransaction`, ws is not responding on confirmed status 

** Transaction seems announced okay as can be retrieved from `account/{publicKey}/transactions` or `transaction/{hash}` etc...

**Comment by Vektrat** [comment]
most likely directly related to #71 , when there's an exception parsing the object it will throw, halting the monitoring feedback

**Comment by rg911** [comment]
and bear in mind that the MosaicHttp also worth checking. Seems it is affected as well
