### ISSUE TITLE
Fetch transactions by Address

### ISSUE THREAD

**Issue by aleixmorgadas** [nemtech/catapult-rest#8]
In the endpoints, it should be possible using the address as well.

- http://localhost:3000/account/{address|publicKey}/transactions
- http://localhost:3000/account/{address|publicKey}/transactions/outgoing
- http://localhost:3000/account/{address|publicKey}/transactions/incoming

### Motivation

Often, you don't know the public key, just the address. Go to the address info, get the public key and then fetch the transactions can be done, but it's not as direct as being able to fetch directly using the Address.

**Comment by evias** [comment]
up on this as it is blocking to client implementations for retrieving account transactions for accounts whose public key is unknown by network.
