### ISSUE TITLE
MosaicDefinitionTransaction mosaicNonce vs nonce

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#82]
According to the Open API 3 spec, 

https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml

the nonce property of MosaicDefinitionTransactionDTO is "mosaicNonce" but the server is returning "nonce" as the JSON below.

The Java SDK heavily relies on the generate clients and DTOs from the Open API spec. If there is an inconsistency like this the DTO won't be parsed correctly. The solution would be to either change the open API spec or change or the catapult-rest model object. What do you think @dgarcia360?

```JSON
{  
   "transaction":{  
      "signature":"7EAEA998D0FA78F96E9CF8FE3AFF3CE39F6FDC67CD38EFEC1670F7BE7C6A3C7AAAAA2BE108126AA855C5548F5BD109B9D4227A9156DC31CF243F501D9E33F10C",
      "signer":"69970C5FB7A72662A6457504851DC11B10B19EB8A7D8C5E22301F1DC7492F292",
      "version":36865,
      "type":16717,
      "maxFee":[  
         0,
         0
      ],
      "deadline":[  
         4002752628,
         24
      ],
      "nonce":1493805961,
      "mosaicId":[  
         319533547,
         672276418
      ],
      "properties":[  
         {  
            "key":0,
            "value":[  
               3,
               0
            ]
         },
         {  
            "key":1,
            "value":[  
               4,
               0
            ]
         },
         {  
            "key":2,
            "value":[  
               100,
               0
            ]
         }
      ]
   },
   "meta":{  
      "hash":"92C12CFC091788B7FF10ACE45DB6B6C37F299152E09DB889C2716118C5FFFF67",
      "merkleComponentHash":"92C12CFC091788B7FF10ACE45DB6B6C37F299152E09DB889C2716118C5FFFF67",
      "height":[  
         11749,
         0
      ],
      "channelName":"confirmedAdded"
   }
}
```

**Comment by Vektrat** [comment]
mongodb hosts`nonce` just as specified in the catbuffer schema https://github.com/nemtech/catbuffer/blob/169a02873584a9a580ffe49eb827995711c6d92c/schemas/mosaic/mosaic_definition.cats#L7

will wait for @dgarcia360 input before getting into premature changes (specially now with all the consistency renaming going on)

**Comment by dgarcia360** [comment]
catapult-rest 0.7.17 + catapult-server 0.6.0.1 (latest stable) returns ``mosaicNonce``.  Next version REST compatible with catapult-server 0.7.0.1 will return just ``nonce``.

The changes are being documented here (still unfinished): https://github.com/nemtech/nem2-openapi/pull/16/files

**Comment by Vektrat** [comment]
REST is up to date and it is nem2-openapi which requires updates, so closing issue here
