### ISSUE TITLE
Add Uint64 formatter to string or hexadecimal

### ISSUE THREAD

**Issue by evias** [nemtech/catapult-rest#84]
Following this PR nemtech/nem2-sdk-typescript-javascript#239, it is being discussed to add a formatter in REST to encode UInt64 as `string` (number or hexadecimal TBC) instead of in the form of an array of numbers.

As each SDK would need a copy of the PR mentioned above, it would make more sense to add the formatter in catapult-rest.

@Vektrat, assigned steven temporarily, can be changed obviously :+1:

**Comment by Vektrat** [comment]
i never liked the array format, so sounds good to me, what opinion does the core team have on this? @Jaguar0625 @gimer @BloodyRookie

**Comment by fboucquez** [comment]
Perfect!

IMHO, I don't see the performance benefit of having high/low number style arrays. SDKs need to convert them back to u64 numbers (like BigInteger in Java), it complicates the rest APIs making them less user-friendly and it complicates SDK mappings. I can understand that high/low can be super performant in catbuffer style serialization but not so sure in standard rest.

I also preferred the string/decimal numbers over hexadecimal numbers for the same reasons above. Unless there is a real performance reason to do it differently, a person should be able to understand the "difficulty" by just looking at http://167.71.13.249:3000/block/1.

Cheers
Fernando

**Comment by Vektrat** [comment]
waiting for final input from @dgarcia360 , i believe to have seen a comment where he suggested different formats

**Comment by rg911** [comment]
> waiting for final input from @dgarcia360 , i believe to have seen a comment where he suggested different formats

you mean this?
by @dgarcia360 - " Thinking more about it, for identifiers (mosaics and namespaces) could be hexa, but for height, amounts, duration, difficulty, scores, and timestamps could be a string."

**Comment by dgarcia360** [comment]
My proposal was to treat all Uint64 arrays as strings except identifiers (mosaic and namespace ids). 

Differently to values, identifiers do not have a meaning on their own. For that reason, we can show them nicely in a shorter form encoding them as hexa. 

Also, it will be compatible with the current endpoint parameters (e.g. /mosaic/<mosaicId (hexa)>).

**Comment by Vektrat** [comment]
Okay, with `Uint64` as `string` do you mean to represent a number in a string format? such as '7862759275' --> `"7862759275"`?

**Comment by dgarcia360** [comment]
Yes, for example:

> UInt64 [3127188303,2974383967] --> string '12774881867138931535'  --> hexa 'B1497F5FBA651B4F'

Ideally should be represented as regular numbers, but not every language supports unsigned large numbers (for example Javascript). To deal with them, we have to represent them in another way. Reducing the problem, it could be a string (encoded as hexa or not) or the array we are using right now.

**Comment by Vektrat** [comment]
we are working on this and will be merged immediately after all the known issues with the wg-standard and elephant 3 are fixed

as agreed, this involves:
- every uint64 (the old two-valued arrays) will be returned as a **numeric string**
- WITH EXCEPTION of (resolved or unresolved) mosaic and namespace identifiers, which will be returned as **HEX strings**
