### ISSUE TITLE
add configuration for CORS to rest.json

### ISSUE THREAD

**Issue by Jaguar0625** [nemtech/catapult-rest#94]
currently `bootstrapper.js` is allowing all:
```
res.header('Access-Control-Allow-Origin', '*');
```

this should at least be configurable

**Comment by Vektrat** [comment]
yep, this was pending (#5 ), will add an option to the config file

**Comment by Vektrat** [comment]
i was just checking this issue... a few questions before proceeding:

handling CORS by just adding an ALLOWED_HOST (basically to be able to replace the `'*'` with a hostname, comes with some limitations and feels a bit cheap (what if we wanted to enable multiple hosts, which is the common provided CORS configuration by API servers? things would get complicated, and we would need to dynamically configure headers)

i was checking if restify provides any CORS plugin, and apparently they dropped support for it a few versions ago ( http://restify.com/docs/4to5/ ) which now points to an external project: 

> CORS
> CORS has been removed from restify core. For CORS support, please use TabDigital’s plugin.

https://github.com/Tabcorp/restify-cors-middleware (which is not free of issues either)

should we adopt this plugin, or juts add the fast single-host option to the config?

**Comment by Vektrat** [comment]
as agreed with the team, we will allow just one host for now, in case we need more in the future we can consider the plugin

i will also dynamically set the `Vary: Origin` header as per specification, i believe it won't have any consequence with just a single host, but the specification is not clear, so having it won't hurt

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching (this spec dictates that it should always be provided if host differs from `'*'`
- https://www.w3.org/TR/cors/#resource-implementation (this spec dictates that it should be provided for the existence of multiple hosts)
